# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example

osx_image: xcode7.1

before_install:
  - gem install cocoapods

script:
- set -o pipefail && xcodebuild test -workspace Example/Tapstream-Segment.xcworkspace -scheme Tapstream-Segment-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint

notifications:
  email: false
